name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Checkout des Repositorys
      - name: Checkout code
        uses: actions/checkout@v4

      # Schritt 2: Setup Java und Android SDK
      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # Schritt 3: Zugang zu Secrets (wenn benötigt, für API-Schlüssel etc.)
      - name: Access Secrets
        env:
          TMDB_API: ${{ secrets.TMDB_API }}
          # Füge hier weitere Secrets hinzu, wenn nötig
        run: |
          cd $GITHUB_WORKSPACE
          echo TMDB_API=$TMDB_API >> local.properties

      # Schritt 4: Bauen der Plugins und der cs3-Datei
      - name: Build Plugins and .cs3 file
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      # Schritt 5: Optional: Push die Builds zurück ins Repository
      - name: Push Builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force
