name: Build Streamcloud Plugin

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout Builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Clean Old Builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 17 (Fix für Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Manuelles Installieren von Android SDK
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo curl -sS -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          sudo unzip -q sdk-tools.zip -d /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo rm sdk-tools.zip
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-31"

      - name: Build Streamcloud Plugin
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/StreamcloudProvider.cs3 $GITHUB_WORKSPACE/builds || echo "Streamcloud Plugin nicht gefunden!"
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push Builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build Streamcloud Plugin - $GITHUB_SHA" || exit 0
          git push --force
