name: Build Streamcloud Plugin

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout Builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Clean Old Builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Install Android SDK
        run: |
          echo "Setting up Android SDK"
          # Install Android Command Line Tools
          sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo curl -sS -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          sudo unzip -q sdk-tools.zip -d /usr/local/lib/android/sdk/cmdline-tools/latest
          sudo rm sdk-tools.zip

          # Set Environment variables
          echo "export ANDROID_HOME=/usr/local/lib/android/sdk" >> $HOME/.bashrc
          echo "export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $HOME/.bashrc
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $HOME/.bashrc
          source $HOME/.bashrc

          # Install required SDK components
          yes | sdkmanager --licenses
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-31" "build-tools;31.0.0"
          
      - name: Build Streamcloud APK
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew assembleRelease
          cp app/build/outputs/apk/release/app-release.apk $GITHUB_WORKSPACE/builds/Streamcloud.apk || echo "Streamcloud APK nicht gefunden!"

      - name: Build BurningSeries Plugin
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/BurningSeriesProvider.cs3 $GITHUB_WORKSPACE/builds || echo "BurningSeries Plugin nicht gefunden!"
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push Builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build Streamcloud APK & BurningSeries Plugin - $GITHUB_SHA" || exit 0
          git push --force
