name: Build

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      # choose your default branch
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Access Secrets
        env:
          # Hier kannst du API-Schlüssel oder andere geheime Daten einbinden, die du für das Plugin benötigst
          TMDB_API: ${{ secrets.TMDB_API }}
          DUMP_API: ${{ secrets.DUMP_API }}
          # Hier kannst du weitere Umgebungsvariablen definieren, die du in deinem Plugin verwendest
        run: |
          cd $GITHUB_WORKSPACE/src
          echo TMDB_API=$TMDB_API >> local.properties
          echo DUMP_API=$DUMP_API >> local.properties
          # Hier kannst du weitere API-Schlüssel und Variablen einfügen

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson  # Hier wird das Plugin gebaut
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Move Kuramanime
        run: |
          rm $GITHUB_WORKSPACE/builds/KuramanimeProvider.cs3 || true
          cp $GITHUB_WORKSPACE/builds/stored/KuramanimeProvider.cs3 $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $G
