name: Build Streamcloud Plugin

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Setup JDK 17
  uses: actions/setup-java@v4
  with:
    distribution: "adopt"
    java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Access Secrets for API tokens
        env:
          STREAMCLOUD_API_KEY: ${{ secrets.STREAMCLOUD_API_KEY }}
          OTHER_API_TOKEN: ${{ secrets.OTHER_API_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/src
          echo STREAMCLOUD_API_KEY=$STREAMCLOUD_API_KEY >> local.properties
          echo OTHER_API_TOKEN=$OTHER_API_TOKEN >> local.properties

      - name: Clean old builds
        run: rm -rf $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Build Streamcloud Plugin
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew buildStreamcloudPlugin
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push Builds to the Repository
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build Streamcloud Plugin $GITHUB_SHA" || exit 0
          git push --force
